### ISSUE TITLE
how to send a PATCH request?

### ISSUE THREAD

**Issue by ycavatars** [jhollingworth/marty#123]
hello, I read `http.js` and found that it doesn't support PATCH method. I try to call `this.request` with option `{method: "patch" ...}` to send a PATCH request. The problem is, I don't know how to handle the promise rejection if an error occurred. Could you tell me where can I get enough information to achieve this? thanks.

**Comment by oliverwoodings** [comment]
Hi @ycavatars, the HttpStateSource uses the [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) polyfill for making the request. When you make a call to `this.request` it calls the fetch API and then handles the response for you (see code [here](https://github.com/jhollingworth/marty/blob/master/lib/stateSources/http.js#L27-L41)). If the server responds with status 400 or greater, Marty will throw the response as an exception. Otherwise it will resolve normally. Therefore you can do the following:

```js
this.request({ method: "patch" ...})
  .then(function (res) {
    console.log("everything went better than expected!");
  })
  .catch(function (res) {
    console.log("something foobar'd");
  });
```

Does that help?

**Comment by ycavatars** [comment]
yes, really thanks :)

**Comment by oliverwoodings** [comment]
I'll do a quick PR for you to add in the PATCH method as a sugar function like the other methods.
