### ISSUE TITLE
Use lodash v3 instead of underscore

### ISSUE THREAD

**Issue by jhollingworth** [jhollingworth/marty#136]
As @jdalton [points out](https://github.com/jhollingworth/marty/pull/38#issuecomment-74934635), [lodash v3 makes cherry picking functions much easier](https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144). I think if we did this instead of requiring in the whole of underscore we could reduce file size significantly

**Comment by hasdavidc** [comment]
not sure if i did something wrong, but i did this in [my fork](https://github.com/hasdavidc/marty/tree/136/use-lodash-over-underscore) and the gzipped file actually ended up jumping to 29.9kb https://github.com/hasdavidc/marty/blob/4925590ec4203afe1f366a66d456f1d2ee967513/dist/marty.min.js.gz, compared to the current 24.3kb gzipped https://github.com/jhollingworth/marty/blob/f83307038b1c268bd7d9ac06610e393b2dfe64c9/dist/marty.min.js.gz

so perhaps not quite as quick of a win, or i'm just missing something right now. i did leave quite a few utility functions in place (https://github.com/hasdavidc/marty/blob/4925590ec4203afe1f366a66d456f1d2ee967513/lib/utils/mindash.js), some of which aren't well optimized (each, extend, and map don't use internal equivalents due to some special cases where each/map receive both objects/arrays, extend has multiple sources in a few places, keeping it from using lodash/internal/baseAssign).

i'm interested in getting the size down, just wanted to leave a comment to say i was working on it

**Comment by jdalton** [comment]
Thanks @hasdavidc. I'll check it out this evening.

**Comment by jdalton** [comment]
You can reduce 29kb to 27kb by using `lodash/internal/bindCallback` for `bind` but in this case there's some heavy methods like `matches()` and `union()` which prevent it from getting much smaller. lodash's `_.matches` supports partial deep matches (so uses bits of `isEqual`). lodash's `union` uses `uniq` which has optimizations for ES6 so is a bit heftier.

**Comment by jdalton** [comment]
I spoke too soon. When I was testing I was bundling mindash alone using some optimized settings but not applying them to the entire build. When I do that I get 21kb for the total build even with those heavier methods.

**Comment by jdalton** [comment]
I'll create a PR.
