### ISSUE TITLE
Question about action creators and (also) rollback

### ISSUE THREAD

**Issue by FoxxMD** [jhollingworth/marty#141]
Hi! Can you clarify some things for me?

So far when I've used action creators I've only been using `this.dispatch` which I understand is to invoke an action handler on my store. Any time I've needed to make an api call it's been using `remotely` on a `fetch` in my stores.

Specifically I'm looking at the marty-chat example application.

[In the room action creator](https://github.com/jhollingworth/marty-chat-example/blob/master/app/actions/roomActionCreators.js)

```
var RoomActionCreators = Marty.createActionCreators({
  createRoom: RoomConstants.CREATE_ROOM(function (name) {
    var room = RoomUtils.createRoom(name);

    this.dispatch(room);

    return RoomHttpAPI.createRoom(room);
  })
});
```

[and then in the room source](https://github.com/jhollingworth/marty-chat-example/blob/master/app/sources/roomHttpAPI.js)

```
createRoom: function (room) {
    var req = {
      url: '/api/rooms',
      body: _.omit(room, 'cid')
    };

    return this.post(req).then(function (res) {
      RoomSourceActionCreators.updateRoom(room.cid, res.body);

      return res.body.id;
    });
  }
});
```

My api calls (using `remotely` from a store) in my source return a source action creator so I'm unclear as to how the above code works.

Can you explain
* the difference between returning an action creator in a source vs. specific data
* the difference between using `this.dispatch` , `return`, and the two in conjunction inside an action creator

I have a vague idea that it has to do with updating data locally vs. remotely but I can't put the pieces together.

---

Along the same line can you give me an example of using rollback in [an action creator](http://martyjs.org/api/action-creators/index.html#dispatch) and [the store](http://martyjs.org/api/stores/index.html#rollback) ?

Thanks!

**Comment by jhollingworth** [comment]
Hey, I've been having a look at that chat example again and it's not 100% correct so apologies for that.

To ask your question...

As you probably know one of the fundamentals of flux is the unidirectional data flow. Any changes you want to make to state (both locally and remotely) have to follow the flow Action creator -> Dispatcher -> Store -> State mixin -> Component.

to use the ``createRoom`` example:

1. The [NewRoom component creates an CREATE_ROOM action](https://github.com/jhollingworth/marty-chat-example/blob/master/app/components/newRoom.js#L49). It doesn't actually use the return value as that would violate the unidirectional data flow principle. The [return in the CREATE_ROOM action creator](https://github.com/jhollingworth/marty-chat-example/blob/master/app/actions/roomActionCreators.js#L13) shouldn't be there and is kinda confusing, sorry about that.
2. In the CREATE_ROOM action creator we [optimistically add the new room locally](https://github.com/jhollingworth/marty-chat-example/blob/master/app/actions/roomActionCreators.js#L11). Going on the assumption that this call will probably succeed we make the application appear by performing the operation earlier and then dealing with the consequences if it fails.
3. The action creator then calls [RoomAPI which makes the call to the remote server](https://github.com/jhollingworth/marty-chat-example/blob/master/app/sources/roomHttpAPI.js#L23). Again the [return](https://github.com/jhollingworth/marty-chat-example/blob/master/app/sources/roomHttpAPI.js#L23) is not necessary since the source action handles is responsible for [creating new actions when the state appears](https://github.com/jhollingworth/marty-chat-example/blob/master/app/sources/roomHttpAPI.js#L24). Again [this return](https://github.com/jhollingworth/marty-chat-example/blob/master/app/sources/roomHttpAPI.js#L26) isn't needed.

Fetching state is largely similar except your source action creator should return a promise. This is because ``remotely`` expects you to return a promise which, when resolved, means the state should be there locally.

```js
getFoo: function() {
  return this.fetch({
    id: 'foo',
    locally: function () {
      return this.state['foo']
    },
    remotely: function () {
      // this expects you to return a promise

      return FooAPI.getFoo();
    }
  });  
}

var FooAPI = Marty.createStateSource({
  type: 'http',
  getFoo: function () {
    return this.get('/foo').then(function (req) {
      FooSourceActionCreators.receiveFoo(req.body);
    });
  }
})
```

Does that make sense?

As for rollbacks, you could do something like this:

```js
createRoom: RoomConstants.CREATE_ROOM(function (name) {
  var room = RoomUtils.createRoom(name);
  var createRoomAction = this.dispatch(room);

  return RoomHttpAPI.createRoom(room, createRoomAction);
})

createRoom: function (room, action) {
  var req = {
    url: '/api/rooms',
    body: _.omit(room, 'cid')
  };

  return this.post(req).then(function (res) {
    RoomSourceActionCreators.updateRoom(room.cid, res.body);

    return res.body.id;
  }).catch(function (error) {
    if (action) {
      action.rollback();
    }

    RoomSourceActionCreators.failedToCreateRoom(room, error);
  });
}
```

However I'm not 100% happy with this approach. It's a little too low level. Having a better way of dealing with failures is the focus for v0.10.

**Comment by jhollingworth** [comment]
I've got rid of the returns in jhollingworth/marty-chat-example#4 so will hopefully bit a bit easier to understand

**Comment by FoxxMD** [comment]
Thanks! This helps tremendously.
