### ISSUE TITLE
ES6 file naming + webpack

### ISSUE THREAD

**Issue by sporto** [jhollingworth/marty#226]
I'm using Webpack to build my front-end. Webpack requires the original source directly. Because you are using .js for ES6 I need to pipe everything through a transpiler (Babel).

This means that I need to tell Webpack to pipe all .js file through Babel, which is unnecessary most of the time. Webpack can be easily configured to just pipe certain files, e.g .es6 extension.

I also tried requiring the file in dist/browser/marty.js but that expects a React global, so not a good alternative.

Would you consider renaming all ES6 files to .es6 or something distinctive?

**Comment by moretti** [comment]
I'm having the same problem, this is because the `browser` field in `package.json` has `marty.is` as entry point rather then `dist/node/marty.js`.

In theory it would be nice to have `browser` pointing to standard commonjs+es5 files so that we don't have to process `node_modules` with babel. In this way we could also remove `babelify` from `dependencies`.

**Comment by FoxxMD** [comment]
:+1: [I was having the same problem](https://gitter.im/jhollingworth/marty?at=5511d0f4c68bbf0b5d01c040) @sporto. I've worked around it by explicitly including `/marty/` in my `babel-loader` test

**Comment by sporto** [comment]
I added as suggested:

```
{ test: /\/marty\//, loader: "babel-loader" },
```

To my webpack config, this solves the issue
